check_payload = ('{"source":{'
                 '"access_key_id":"apiKey123",'
                 '"secret_access_key":"secretKey321"'
                 '},'
                 '"version":{"env":"dev"}}')
in_payload = ('{"source":{'
              '"access_key_id":"apiKey123",'
              '"secret_access_key":"secretKey321"'
              '},'
              '"version":{"env":"dev"}}')
out_deploy_payload = ('{"params":{'
               '"env":"dev",'
               '"deploy": true,'
               '"artifact_file": "artifact/package.zip",'
               '"config_file": "source/ci'
               '"},'
               '"source":{'
               '"access_key_id":"apiKey123",'
               '"secret_access_key":"secretKey321'
               '"},'
               '"version":{"env":"dev"}}')
out_remove_payload = ('{"params":{'
               '"env":"dev",'
               '"remove": true,'
               '"artifact_file": "artifact/package.zip",'
               '"config_file": "source/ci'
               '"},'
               '"source":{'
               '"access_key_id":"apiKey123",'
               '"secret_access_key":"secretKey321'
               '"},'
               '"version":{"env":"dev"}}')
